site_name: Amazon MSK Train-The-Trainer Workshop
repo_name: "vasveena/amazon-msk-ttt-workshop"
repo_url: "https://github.com/vasveena/amazon-msk-ttt-workshop"
docs_dir: "docs"
theme:
 name: material
 features:
   - tabs
nav:
  - Introduction
  - Setup
  - Part 1:
    - Kafka overview & Amazon MSK Cluster Creation
      - 1 - Prerequisites
      - 2 - Launching MSK cluster (Provisoned)
  - Part 2: 
    - Open Monitoring Lab 
  - Part 3: 
    - Kafka Migration Lab - MSK to MSK Serverless
  - Part 4: 
    - Building a Serverless Apache Kafka Data Pipeline:
      - 1 - Introduction: 'day1/Part 4/1_Intro/exercise.md'
      - 2 - Setup MSK Serverless cluster: 'day1/Part 4/2_Setup/exercise.md'
      - 3 - Produce clickstream data to MSK Serverless using Elastic Container Service: 'day1/Part 4/3_Producer/exercise.md'
      - 4 - Consume data from MSK Serverless using Lambda: 'day1/Part 4/4_LambdaConsumer/exercise.md'
      - 5 - Create Quicksight Dashboard: 'day1/Part 4/5_QS_Dashboard/exercise.md'
      - 6 - Consume using Kinesis Data Analytics and write to Amazon OpenSearch Service: 'day1/Part 4/6_KDA_Consumer/exercise.md'  
  - Part 5:
    - MSK Connect Lab 
  - Part 6: 
    - MSK Integration with Athena and Redshift

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite
    - attr_list
    - md_in_html
