site_name: Amazon MSK Train-The-Trainer Workshop
repo_name: "vasveena/amazon-msk-ttt-workshop"
repo_url: "https://github.com/vasveena/amazon-msk-ttt-workshop"
docs_dir: "docs"
theme:
  name: material
  features:
    - tabs
nav:
  - Introduction: 'index.md'
  - Setup: 'setup.md'
  - Part 1:
    - Kafka overview & Amazon MSK Cluster Creation:
      - 1 - Overview: 'day1/part1/overview/exercise.md'
      - 2 - Prerequisites: 'day1/part1/Prerequisites/exercise.md'
      - 3 - Launching MSK cluster (Provisoned)(Console): 'day1/part1/1_provisoned/exercise.md'
      - 4 - Launching MSK cluster (Provisoned)(CLI): 'day1/part1/2_cli/exercise.md'
  - Part 2: 
    - Open Monitoring Lab:
      - 1 - Overview: 'day1/part2/intro/exercise.md'
      - 2 - Setup: 'day1/part2/setup/exercise.md'
      - 3 - Run Prometheus: 'day1/part2/run_prometheus/exercise.md'
      - 4 - Run Grafana: 'day1/part2/run_grafana/exercise.md'
  - Part 3: 
    - Kafka Migration Lab - MSK to MSK Serverless
  - Part 4: 
    - Building a Serverless Apache Kafka Data Pipeline:
      - 1 - Introduction: 'day2/part4/1_Intro/exercise.md'
      - 2 - Setup MSK Serverless cluster: 'day2/part4/2_Setup/exercise.md'
      - 3 - Produce clickstream data to MSK Serverless using Elastic Container Service: 'day2/part4/3_Producer/exercise.md'
      - 4 - Consume data from MSK Serverless using Lambda: 'day2/part4/4_LambdaConsumer/exercise.md'
      - 5 - Create Quicksight Dashboard: 'day2/part4/5_QS_Dashboard/exercise.md'
      - 6 - Consume using Kinesis Data Analytics and write to Amazon OpenSearch Service: 'day2/part4/6_KDA_Consumer/exercise.md'  
  - Part 5: 
    - MSK Integration with Athena and Redshift:
      - 1 - Architecture Introduction: 'day2/part5/overview/exercise.md'
      - 2 - Prerequisites: 'day2/part5/Prerequisites/exercise.md'
      - 3 - Integration with Athena: 'day2/part5/athena/exercise.md'
      - 4 - Integration with Redshift: 'day2/part5/redshift/exercise.md'
      
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite
    - attr_list
    - md_in_html
